### ISSUE TITLE
Z906.cpp compile error

### ISSUE THREAD

**Issue by LucianTothezan** [LewisSmallwood/IoT-Logitech-Z906#1]
Hello,
i was trying to compile your project onto a D1 mini(ESP 8266) but i get an error and I do not have the propper knowledge to interpret it: 
"
   int Z906::cmd(uint8_t cmd_a, uint8_t cmd_b) {
    // Update the internal status buffer with the current device status
    update();

    // Normalize volume to the range 0...255 if applicable
    if (cmd_a == MAIN_LEVEL || cmd_a == REAR_LEVEL || cmd_a == CENTER_LEVEL || cmd_a == SUB_LEVEL) {
        cmd_b = static_cast<uint8_t>((static_cast<uint16_t>(cmd_b) * MAX_VOL) / 255);
    }

    // Update the specified parameter in the internal status buffer
    status[cmd_a] = cmd_b;

    // Update the checksum in the status buffer
    status[STATUS_CHECKSUM] = LRC(status, status_len);

    // Send the updated status buffer to the Z906 device
    write(status, status_len);

    // Discard the acknowledgment (ACK) message to maintain a clean serial buffer
    flush();
} 
"
it sais that is should have a return or void somwhere . i added a return 0; but i am not sure if it is ok.

Also, i see that the status for power always returns the 0 value. is it because it is defined as GET_STATUS and it should be defined as STATUS_STBY according to the data in the serial command table?

**Comment by 3limin4tor** [comment]
Having same problem, was very excited about this because i tried to get my z906 wifi enabled for long time. unfortunately, i'm not experienced at all with arduino and esp8266. Acutally it took me more than 3 hours until i found out what i actually had to do with the files, still i'm an experienced programmer but really not in esp / arduino stuff... a very small guide what to actually do with the files might also help others

**Comment by LucianTothezan** [comment]
I made it work eventually. I can send you the needed data if you are still interrested

**Comment by 3limin4tor** [comment]
i also managed to get it working as well. I have changned the type of the cmd (param,param) function to void in z906.h and cpp file but what still doesn't work is the power state request. (endpoint /power) So yes please let me know how you fixed it

**Comment by LucianTothezan** [comment]
glad to hear you figured that part out :).  as for the power state, it is actually not defined in the .cpp file. So i added the bolded lines here bellow:

in the .cpp file i added the here below **Bolded lines**.

"

int Z906::request(uint8_t cmd) {

if (update()) {

// Return specific data based on the provided command

if (cmd == VERSION) {

// Combine version bytes to form a single integer

return status[STATUS_VER_C] + 10 * status[STATUS_VER_B] + 100 * status[STATUS_VER_A];

}

if (cmd == CURRENT_INPUT) {

// Increment the current input value by 1

return status[STATUS_CURRENT_INPUT] + 1;

}

**if (cmd == GET_STATUS) {

// Get power status

return status[STATUS_STBY];

}**

"

**Comment by LewisSmallwood** [comment]
Hi everyone, thanks for raising the issue. I'm in the middle of moving house, so I haven't had a chance to sort this yet.
Seems you were able to get it working though ☺️ 
@3limin4tor, if you would like to raise a PR, I can get your changes merged in.
I will have the Web UI finished soon: https://lewissmallwood.github.io/IoT-Logitech-Z906/
