### ISSUE TITLE
latest version not passing Arduino IDE compile phase

### ISSUE THREAD

**Issue by LucianTothezan** [LewisSmallwood/IoT-Logitech-Z906#3]
Hello. after the last pdates in the files, i cannot compile the project in Arduino IDE. Can You please check why?

**Comment by 3limin4tor** [comment]
What is the error? But i have an idea: I made some changes on the environment file as well, as i didn't liked the naming so much. Also i have added additional setting for hostname and mdns hostname. LewisSmallwood took over that changes. So i think this is the cause of your issue. Make sure you copy / paste the current example-environment file and adjust the settings for your wifi and if wished, hostname (new in environment file). Should work then.

**Comment by LucianTothezan** [comment]
In file included from C:\Users\lucia\Downloads\Compressed\IoT-Logitech-Z906-main\IoT-Logitech-Z906-main.ino:6:
C:\Users\lucia\Downloads\Compressed\IoT-Logitech-Z906-main\environment.h:20:1: error: cannot convert '<brace-enclosed initializer list>' to 'const char*' in initialization
   20 | };
      | ^

exit status 1

Compilation error: cannot convert '<brace-enclosed initializer list>' to 'const char*' in initialization

**Comment by LewisSmallwood** [comment]
Hi @LucianTothezan, sorry about this.
I have updated the example `environment.h` file to show the correct syntax for the network_settings.
