### ISSUE TITLE
Keep getting status disconnected

### ISSUE THREAD

**Issue by rosconap** [LewisSmallwood/IoT-Logitech-Z906#6]
I installed the software with the arduino editor on a ESP8266 (nodemcu v3) and connected the setup as showed in the docs with a rewirable FEMALE plug layout.

I tried the following but it all gave the same results:

- I used the pin layout as described in the README with a rewirable female connector
- I attached the wires directly attached to the subwoofer
- Started with the `http://nodemcu/power/on`
- Switched the RX and TX connection just to be sure.
- Attached the 3 ground pins to all the 3 ground pins on the nodemcu (docs said it should not matter because ground is all connected as one.)

The nodemcu starts up and is reachable via HTTP with all tries and I keep getting: `{"status": "disconnected"}` on every HTTP GET call i try and i am running a bit out of idea's. I would hope you could point me in the right direction on how to debug this further.

**Comment by LucianTothezan** [comment]
> I installed the software with the arduino editor on a ESP8266 (nodemcu v3) and connected the setup as showed in the docs with a rewirable FEMALE plug layout.
> 
> I tried the following but it all gave the same results:
> 
> * I used the pin layout as described in the README with a rewirable female connector
> * I attached the wires directly attached to the subwoofer
> * Started with the `http://nodemcu/power/on`
> * Switched the RX and TX connection just to be sure.
> * Attached the 3 ground pins to all the 3 ground pins on the nodemcu (docs said it should not matter because ground is all connected as one.)
> 
> The nodemcu starts up and is reachable via HTTP with all tries and I keep getting: `{"status": "disconnected"}` on every HTTP GET call i try and i am running a bit out of idea's. I would hope you could point me in the right direction on how to debug this further.

Hello. I suppose You defined in the speciffic file the wifi connection credetials speciffic to Your router?

**Comment by LewisSmallwood** [comment]
Hi @rosconap, sorry to hear you're experiencing problems with the setup. I did experience this issue once when setting mine up. It was down to the pins being connected incorrectly. Although the troubleshooting steps you took sound great.

You mentioned you're using a female plug. The pin-out diagram in the readme used a male plug.
Whilst I think it's the same for the female one, it would be worth double-checking.

DE-15 Pin | ESP8266 Pin
-- | --
3 | GND
6 | GND
11 | 3V
12 | RX
13 | TX
15 | GND

It sounds as if your 3V and Ground are fine, if you've got it powered up.

In terms of troubleshooting steps, if you're able to plug the original console back in to verify it is all working as it should that would be great. 

Once it's in a powered-on state, you could try swapping the consoles (while it is on) to confirm you can make a connection.

It might be also worth double-checking that the Console Enable pin 15 is definitely grounded.

**Comment by rosconap** [comment]
Problem solved. I attached the Dupont wires directly to the subwoofer without the DE-15 connector according to the provided layout and it worked. Must be a faulty connector somewhere.

Thank you so much for your feedback and this project.
